language: r
sudo: required
cache: packages
dist: trusty

warnings_are_errors: false

notifications:
  email:
    - leo.lahti@iki.fi


r_packages:
  - broom
  - Cairo
  - classInt
  - curl  
  - devtools
  - ggplot2
  - httr
  - jsonlite
  - knitr  
  - lubridate  
  - gdalUtils
  - geojson  
  - geojsonio
  - geojsonlint
  - jqr    
  - mapview
  - mapproj
  - plotrix
  - protolite
  - rgdal
  - RColorBrewer
  - readr
  - rmarkdown
  - rmapshaper  
  - roxygen2
  - rsdmx
  - rvest  
  - sf
  - sp  
  - tmap
  - tmaptools  
  - testthat
  - V8
  
r_github_packages:
  - jimhester/covr
  - r-dbi/DBI
  - r-dbi/RPostgres


addons:
  postgresql: "9.6"
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
      - libprotobuf-dev
      - protobuf-compiler
      - libv8-3.14-dev
      - libjq-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - libjson-c-dev
      - postgresql-server-dev-9.6

env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - GITHUB_REPO: ropengov/eurostat

r_build_args: "--no-resave-data --no-build-vignettes"
r_check_args: "--as-cran --no-build-vignettes"    

apt_packages:
  - libudunits2-dev
  - udunits2
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - libcairo2-dev
  - protobuf-compiler
  - valgrind
  - libgdal20
  - libspatialite-dev 
  - libproj-dev
  - libgeos-dev
  - libgdal1-dev
  - libgdal-dev
  - libgeos-c1v5
  - libjq-dev
  - netcdf-bin

before_install:
  - pip install --user codecov
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler
  - sudo apt-get install libssl-dev
  - sudo apt-get install libcairo2-dev  
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get --yes install npm

  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)

  # activate liblwgeom by:
  - sudo ldconfig
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - psql -d postgis -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"
  # - R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'


  - Rscript -e 'install.packages("broom",repos="http://cran.us.r-project.org")'
  - Rscript -e 'install.packages("classInt")'
  - Rscript -e 'install.packages("jsonlite")'
  - Rscript -e 'install.packages("curl")'
  - Rscript -e 'install.packages("httr")'      
  - Rscript -e 'install.packages("RColorBrewer")'     
  - Rscript -e 'install.packages("sp")'     
  - Rscript -e 'install.packages("readr")'     
  - Rscript -e 'install.packages("Cairo")'     
  - Rscript -e 'install.packages("ggplot2")'     
  - Rscript -e 'install.packages("lubridate")'     
  - Rscript -e 'install.packages("mapproj")'     
  - Rscript -e 'install.packages("plotrix")'     
  - Rscript -e 'install.packages("rmarkdown")'     
  - Rscript -e 'install.packages("roxygen2")'     
  - Rscript -e 'install.packages("rsdmx")'     
  - Rscript -e 'install.packages("rvest")'     
  - Rscript -e 'install.packages("testthat")'     
  - Rscript -e 'install.packages("knitr")'
  - Rscript -e 'install.packages("tmap", repos="http://cran.us.r-project.org")'
  - Rscript -e 'install.packages("sf", repos="http://cran.us.r-project.org")'


install:
  - . $HOME/.nvm/nvm.sh  
  - nvm install stable
  - nvm use stable
  - npm install -g mapshaper
  - npm install -g geojson  

r:
- release
- devel

after_success:
  #- Rscript -e 'covr::codecov()'
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - R -q -e 'covr::codecov(quiet = FALSE)'

